//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFiestDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Customer_RoleInfo
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int RoleInfoId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RoleInfo RoleInfo { get; set; }
    }
}
